package com.gno.erbs.erbs.stats.model.erbs.matches.item.weapon

import com.gno.erbs.erbs.stats.model.erbs.matches.item.SearchItem

data class ItemWeapon(
    val attackPower: Float?,
    val attackPowerByLv: Float?,
    val attackRange: Float?,
    val attackSpeedRatio: Float?,
    val attackSpeedRatioByLv: Float?,
    override val code: Int?,
    val consumable: Boolean?,
    val cooldownLimit: Float?,
    val cooldownReduction: Float?,
    val craftAnimTrigger: String?,
    val criticalStrikeChance: Float?,
    val criticalStrikeDamage: Float?,
    val defense: Float?,
    val defenseByLv: Float?,
    val exclusiveProducer: Float?,
    val fullDecreaseRecoveryToBasicAttackMelee: Float?,
    val fullDecreaseRecoveryToBasicAttackRange: Float?,
    val fullDecreaseRecoveryToSkillMelee: Float?,
    val fullDecreaseRecoveryToSkillRange: Float?,
    val halfDecreaseRecoveryToBasicAttackMelee: Float?,
    val halfDecreaseRecoveryToBasicAttackRange: Float?,
    val halfDecreaseRecoveryToSkillMelee: Float?,
    val halfDecreaseRecoveryToSkillRange: Float?,
    val hpRegen: Float?,
    val hpRegenRatio: Float?,
    val increaseBasicAttackDamage: Float?,
    val increaseBasicAttackDamageByLv: Float?,
    val increaseBasicAttackDamageRatioByLv: Float?,
    val increaseSkillDamage: Float?,
    val increaseSkillDamageByLv: Float?,
    val increaseSkillDamageRatio: Float?,
    val increaseSkillDamageRatioByLv: Float?,
    val initialCount: Float?,
    val itemGrade: String?,
    val itemType: String?,
    val lifeSteal: Float?,
    val makeMaterial1: Float?,
    val makeMaterial2: Float?,
    val maxHp: Float?,
    val maxHpByLv: Float?,
    val maxSP: Float?,
    val moveSpeed: Float?,
    val moveSpeedOutOfCombat: Float?,
    override val name: String?,
    val penetrationDefense: Float?,
    val penetrationDefenseRatio: Float?,
    val preventBasicAttackDamagedByLv: Float?,
    val preventBasicAttackDamagedRatioByLv: Float?,
    val preventSkillDamagedByLv: Float?,
    val preventSkillDamagedRatioByLv: Float?,
    val sightRange: Float?,
    val spRegen: Float?,
    val spRegenRatio: Float?,
    val stackable: Float?,
    val trapDamageReduce: Float?,
    val trapDamageReduceRatio: Float?,
    val weaponType: String?
) : SearchItem

